### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by brunomcpena** [mobeigi/fb2cal#10]
C:\Git\fb2cal\fb2cal\src>python ./fb2cal.py
C:\Users\Home\AppData\Local\Programs\Python\Python37\lib\site-packages\oauth2client\_helpers.py:255: UserWarning: Cannot access token.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
Traceback (most recent call last):
  File "./fb2cal.py", line 386, in <module>
    main()
  File "./fb2cal.py", line 72, in main
    service = google_api_authenticate()
  File "./fb2cal.py", line 151, in google_api_authenticate
    flow = client.flow_from_clientsecrets('credentials.json', SCOPES)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python37\lib\site-packages\oauth2client\_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python37\lib\site-packages\oauth2client\client.py", line 2135, in flow_from_clientsecrets
    cache=cache)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python37\lib\site-packages\oauth2client\clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python37\lib\site-packages\oauth2client\clientsecrets.py", line 126, in _loadfile
    return _validate_clientsecrets(obj)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python37\lib\site-packages\oauth2client\clientsecrets.py", line 101, in _validate_clientsecrets
    prop_name, client_type))
oauth2client.clientsecrets.InvalidClientSecretsError: Missing property "redirect_uris" in a client type of "web".

**Comment by mobeigi** [comment]
Your `credentials.json` contents are wrong. Where did you get them from?

Go here: https://developers.google.com/drive/api/v3/quickstart/go

Click **Enable the drive API** and **download client configuration**

The file contents should a little like this:

```
{"installed":{"client_id":"123test.apps.googleusercontent.com",
"project_id":"calendar-project-123","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token",
"auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
"client_secret":"blahblahsecret","redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}}
```
