### ISSUE TITLE
fb2cal stops working with login alert (FB Issue)

### ISSUE THREAD

**Issue by adilsond** [mobeigi/fb2cal#111]
I reinstalled  fb2cal after a few days ago and, now I got this error with a Facebook uncommon login alert

[2023-12-24 13:22:50,451] fb2cal INFO (<module>) Starting fb2cal v1.2.4 (Production) [https://git.io/fjMwr]
[2023-12-24 13:22:50,451] fb2cal INFO (<module>) This project is released under the GPLv3 license.
[2023-12-24 13:22:50,451] fb2cal INFO (<module>) Attemping to parse config file...
[2023-12-24 13:22:50,451] fb2cal INFO (<module>) Config successfully loaded.
[2023-12-24 13:22:50,451] fb2cal INFO (<module>) Logging level set to: DEBUG
[2023-12-24 13:22:50,451] fb2cal INFO (<module>) Attemping to authenticate with Facebook...
[2023-12-24 13:22:50,452] urllib3.connectionpool DEBUG (_new_conn) Starting new HTTP connection (1): www.facebook.com:80
[2023-12-24 13:22:50,502] urllib3.connectionpool DEBUG (_make_request) http://www.facebook.com:80 "GET /login.php HTTP/1.1" 301 0
[2023-12-24 13:22:50,503] urllib3.connectionpool DEBUG (_new_conn) Starting new HTTPS connection (1): www.facebook.com:443
[2023-12-24 13:22:50,757] urllib3.connectionpool DEBUG (_make_request) https://www.facebook.com:443 "GET /login.php HTTP/1.1" 200 None
[2023-12-24 13:22:50,810] urllib3.connectionpool DEBUG (_make_request) http://www.facebook.com:80 "GET /login.php HTTP/1.1" 301 0
[2023-12-24 13:22:50,994] urllib3.connectionpool DEBUG (_make_request) https://www.facebook.com:443 "GET /login.php HTTP/1.1" 200 None
[2023-12-24 13:22:53,391] urllib3.connectionpool DEBUG (_make_request) https://www.facebook.com:443 "POST /login/device-based/regular/login/?login_attempt=1&lwv=100 HTTP/1.1" 302 0
[2023-12-24 13:22:53,573] urllib3.connectionpool DEBUG (_make_request) https://www.facebook.com:443 "GET / HTTP/1.1" 200 0
[2023-12-24 13:22:53,575] fb2cal INFO (<module>) Successfully authenticated with Facebook.
[2023-12-24 13:22:53,575] fb2cal INFO (<module>) Fetching all Birthdays via BirthdayCometRootQuery endpoint...
[2023-12-24 13:22:53,821] urllib3.connectionpool DEBUG (_make_request) https://www.facebook.com:443 "GET /events/birthdays/ HTTP/1.1" 200 None
[2023-12-24 13:22:54,280] urllib3.connectionpool DEBUG (_make_request) https://www.facebook.com:443 "POST /api/graphql/ HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/home/fb2cal/.local/share/virtualenvs/fb2cal-L-4I1o8G/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/fb2cal/fb2cal/fb2cal/__main__.py", line 71, in <module>
    birthday_comet_monthly_json = facebook_browser.query_graph_ql_birthday_comet_monthly(offset_month)
  File "/home/fb2cal/fb2cal/fb2cal/facebook_browser.py", line 136, in query_graph_ql_birthday_comet_monthly
    return response.json()
  File "/home/fb2cal/.local/share/virtualenvs/fb2cal-L-4I1o8G/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

And no birthdays was retrived. Maybe Mark close this endpoint.

**Comment by mobeigi** [comment]
Thanks for the report @adilsond!

The endpoint still works the same. Looks like they added new tokens to the page and the regexp was picking the wrong one.
Fixed in https://github.com/mobeigi/fb2cal/pull/112

Will release version `1.3.0` with the fix included soon.
