### ISSUE TITLE
Add one-click installation support for non-devs

### ISSUE THREAD

**Issue by mobeigi** [mobeigi/fb2cal#15]
A lot of non-dev users have trouble setting this script up.
For such people, a one-click solution would be ideal.

Rough outline of what tool would do:

1. Install script (maybe using PyInstaller to strip away python dependency)
2. Prompt user for required information (FB user/pass and ICS name)
3. Automatically add task to cronjob/Task Scheduler/Automater based on OS.

**Comment by gioluca2** [comment]
Could you add a windows installer? I follow your guide, but I have this error:
fb2cal ERROR (main) Failed to authenticate with Facebook with email luca.casarin@outlook.it. Please check provided email/password.
Traceback (most recent call last):
  File "./fb2cal.py", line 698, in <module>
    main()
  File "./fb2cal.py", line 113, in main
    raise SystemError
SystemError

**Comment by mobeigi** [comment]
I made a quick setup video for those interested until this feature is implemented:

[![fb2cal Setup Guide for Non-Devs [Windows]](http://img.youtube.com/vi/UnsbV8EJ8-Y/0.jpg)](http://www.youtube.com/watch?v=UnsbV8EJ8-Y "fb2cal Setup Guide for Non-Devs [Windows]")

**Comment by Shasties** [comment]
Might it be possible to provide a compiled .exe using something like pyinstaller in a release with some instructions for adding info to a config file? Or use some library to provide a simple gui and remove the config file dependency entirely?

**Comment by mobeigi** [comment]
> Might it be possible to provide a compiled .exe using something like pyinstaller in a release with some instructions for adding info to a config file? Or use some library to provide a simple gui and remove the config file dependency entirely?

Yeah, that would work well.
