### ISSUE TITLE
KeyError: 'LOGGING' 

### ISSUE THREAD

**Issue by jonicunha** [mobeigi/fb2cal#20]
PS C:\Users\jonic\Desktop\fb2cal-master_1.0.2\fb2cal-master\src> python .\fb2cal.py
[2019-08-02 19:45:27,926] fb2cal INFO (<module>) Starting fb2cal v1.0.2 (Production) [https://git.io/fjMwr]
[2019-08-02 19:45:27,926] fb2cal INFO (<module>) This project is released under the GPLv3 license.
[2019-08-02 19:45:27,926] fb2cal INFO (main) Attemping to parse config file config.ini...
[2019-08-02 19:45:27,927] fb2cal INFO (main) Config successfully loaded.
Traceback (most recent call last):
  File ".\fb2cal.py", line 732, in <module>
    main()
  File ".\fb2cal.py", line 82, in main
    logger.setLevel(getattr(logging, config['LOGGING']['level']))
  File "C:\Users\jonic\AppData\Local\Programs\Python\Python37\lib\configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'LOGGING'

**Comment by mobeigi** [comment]
Are you using the latest `config.ini` version?

It looks a little like this now:
```
; Rename this file to config.ini and fill in required information below
[AUTH]
fb_email = 
fb_pass = 

[DRIVE]
upload_to_drive = True
drive_file_id = 
ics_file_name = birthdays.ics

[FILESYSTEM]
save_to_file = False
ics_file_path = ./birthdays.ics

[LOGGING]
level = INFO
```
