### ISSUE TITLE
Followed every step and stuck here

### ISSUE THREAD

**Issue by AntoineZoghbi** [mobeigi/fb2cal#33]
config file setup, google drive setup and all requirements downloaded.
When I run the .py file I get this error:

python ./fb2cal.py
  File "./fb2cal.py", line 51
    return f'{self.name} ({self.day}/{self.month})'
                                                  ^
SyntaxError: invalid syntax

**Comment by mobeigi** [comment]
Are you running python2 instead of python3.6+?

**Comment by AntoineZoghbi** [comment]
Thank you for the quick response.
I made sure I am running python3.6+

**Comment by AntoineZoghbi** [comment]
And this happened:
python3 ./fb2cal.py
Traceback (most recent call last):
  File "./fb2cal.py", line 25, in <module>
    import mechanicalsoup
ModuleNotFoundError: No module named 'mechanicalsoup'

**Comment by AntoineZoghbi** [comment]
And I did pip install all requirements

**Comment by AntoineZoghbi** [comment]
You were right my mac was running python2 since I had both installed!
I got another small issue here: 
Antoines-MacBook-Pro:src antoinezoghbi$ python3 ./fb2cal.py
[2019-08-14 11:43:16,147] fb2cal INFO (<module>) Starting fb2cal v1.0.2 (Production) [https://git.io/fjMwr]
[2019-08-14 11:43:16,147] fb2cal INFO (<module>) This project is released under the GPLv3 license.
[2019-08-14 11:43:16,147] fb2cal INFO (main) Attemping to parse config file config.ini...
[2019-08-14 11:43:16,148] fb2cal INFO (main) Config successfully loaded.
[2019-08-14 11:43:16,149] fb2cal INFO (main) Logging level set to: INFO
[2019-08-14 11:43:16,149] fb2cal INFO (main) Authenticating with Google Drive API...
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access token.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
Traceback (most recent call last):
  File "./fb2cal.py", line 812, in <module>
    main()
  File "./fb2cal.py", line 101, in main
    service = google_drive_api_authenticate()
  File "./fb2cal.py", line 274, in google_drive_api_authenticate
    flow = client.flow_from_clientsecrets('credentials.json', SCOPES)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oauth2client/client.py", line 2135, in flow_from_clientsecrets
    cache=cache)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 126, in _loadfile
    return _validate_clientsecrets(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 101, in _validate_clientsecrets
    prop_name, client_type))
oauth2client.clientsecrets.InvalidClientSecretsError: Missing property "redirect_uris" in a client type of "web".

**Comment by AntoineZoghbi** [comment]
Got it all working. Thanks !
