### ISSUE TITLE
Stuck after running src/fb2cal.py

### ISSUE THREAD

**Issue by cheerysideup** [mobeigi/fb2cal#38]
Here is the error:

Jias-MBP:fb2cal-master jiawen$ python3 src/fb2cal.py
[2019-08-26 21:00:52,728] fb2cal INFO (<module>) Starting fb2cal v1.0.3 (Production) [https://git.io/fjMwr]
[2019-08-26 21:00:52,728] fb2cal INFO (<module>) This project is released under the GPLv3 license.
[2019-08-26 21:00:52,728] fb2cal INFO (main) Attemping to parse config file config.ini...
[2019-08-26 21:00:52,729] fb2cal INFO (main) Config successfully loaded.
[2019-08-26 21:00:52,729] fb2cal INFO (main) Logging level set to: INFO
[2019-08-26 21:00:52,729] fb2cal INFO (main) Authenticating with Google Drive API...
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access token.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
Traceback (most recent call last):
  File "src/fb2cal.py", line 813, in <module>
    main()
  File "src/fb2cal.py", line 102, in main
    service = google_drive_api_authenticate()
  File "src/fb2cal.py", line 275, in google_drive_api_authenticate
    flow = client.flow_from_clientsecrets('credentials.json', SCOPES)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client/client.py", line 2135, in flow_from_clientsecrets
    cache=cache)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client/clientsecrets.py", line 126, in _loadfile
    return _validate_clientsecrets(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client/clientsecrets.py", line 101, in _validate_clientsecrets
    prop_name, client_type))
oauth2client.clientsecrets.InvalidClientSecretsError: Missing property "redirect_uris" in a client type of "web".

**Comment by mobeigi** [comment]
Your credentials.json is missing the `redirect_uris` component.

Try the solution mentioned here:
https://stackoverflow.com/a/48364427/1800854

It should look something like this:
`{"installed":{"client_id":"22222222222-snip.apps.googleusercontent.com","project_id":"fb2cal-222222","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"lXcpV8Hgl68U9SE-c-UzFscG","redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}}
`

**Comment by cheerysideup** [comment]
I added in http://localhost:8080/oauth2callback under "Authorised redirect URIs"

This is the new code I got:
`{"web":{"client_id":"1017050034946-r1btej81bnch452nh3jnmi8k03k7qlcr.apps.googleusercontent.com","project_id":"quickstart-1566826785211","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","redirect_uris":["http://localhost:8080/oauth2callback"],"javascript_origins":["http://localhost:8000"]}}`

Obtained the following issue instead:

```
Jias-MBP:fb2cal-master jiawen$ python3 src/fb2cal.py
[2019-08-27 22:49:50,128] fb2cal INFO (<module>) Starting fb2cal v1.0.3 (Production) [https://git.io/fjMwr]
[2019-08-27 22:49:50,128] fb2cal INFO (<module>) This project is released under the GPLv3 license.
[2019-08-27 22:49:50,129] fb2cal INFO (main) Attemping to parse config file config.ini...
[2019-08-27 22:49:50,131] fb2cal INFO (main) Config successfully loaded.
[2019-08-27 22:49:50,132] fb2cal INFO (main) Logging level set to: INFO
[2019-08-27 22:49:50,132] fb2cal INFO (main) Authenticating with Google Drive API...
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access token.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
Traceback (most recent call last):
  File "src/fb2cal.py", line 813, in <module>
    main()
  File "src/fb2cal.py", line 102, in main
    service = google_drive_api_authenticate()
  File "src/fb2cal.py", line 275, in google_drive_api_authenticate
    flow = client.flow_from_clientsecrets('credentials.json', SCOPES)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client/client.py", line 2135, in flow_from_clientsecrets
    cache=cache)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client/clientsecrets.py", line 126, in _loadfile
    return _validate_clientsecrets(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client/clientsecrets.py", line 101, in _validate_clientsecrets
    prop_name, client_type))
oauth2client.clientsecrets.InvalidClientSecretsError: Missing property "redirect_uris" in a client type of "web".
Jias-MBP:fb2cal-master jiawen$ python3 src/fb2cal.py
[2019-08-28 06:10:49,309] fb2cal INFO (<module>) Starting fb2cal v1.0.3 (Production) [https://git.io/fjMwr]
[2019-08-28 06:10:49,310] fb2cal INFO (<module>) This project is released under the GPLv3 license.
[2019-08-28 06:10:49,310] fb2cal INFO (main) Attemping to parse config file config.ini...
[2019-08-28 06:10:49,312] fb2cal INFO (main) Config successfully loaded.
[2019-08-28 06:10:49,313] fb2cal INFO (main) Logging level set to: INFO
[2019-08-28 06:10:49,313] fb2cal INFO (main) Authenticating with Google Drive API...
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access token.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
Traceback (most recent call last):
  File "src/fb2cal.py", line 813, in <module>
    main()
  File "src/fb2cal.py", line 102, in main
    service = google_drive_api_authenticate()
  File "src/fb2cal.py", line 275, in google_drive_api_authenticate
    flow = client.flow_from_clientsecrets('credentials.json', SCOPES)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client/client.py", line 2135, in flow_from_clientsecrets
    cache=cache)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client/clientsecrets.py", line 126, in _loadfile
    return _validate_clientsecrets(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/oauth2client/clientsecrets.py", line 101, in _validate_clientsecrets
    prop_name, client_type))
oauth2client.clientsecrets.InvalidClientSecretsError: Missing property "client_secret" in a client type of "web".
```

**Comment by mobeigi** [comment]
Don't try to manipulate the credentials file yourself. You should be able to configure all the settings you need online then download the **credentials.json** file directly from the Google Drive website.

These steps should really be all you need:
https://developers.google.com/drive/api/v3/enable-drive-api

If you like we can do 1-on-1 chat over Messenger or Discord to try and debug in real time (you can add me on these networks via links on my site https://mobeigi.com/)
