### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by albertoZurini** [mobeigi/fb2cal#60]
Here the trace for the error I got (maybe due to 2SA?)
```
[2020-04-27 08:45:48,071] fb2cal INFO (<module>) Starting fb2cal v1.0.4 (Production) [https://git.io/fjMwr]
[2020-04-27 08:45:48,071] fb2cal INFO (<module>) This project is released under the GPLv3 license.
[2020-04-27 08:45:48,071] fb2cal INFO (main) Attemping to parse config file config.ini...
[2020-04-27 08:45:48,071] fb2cal INFO (main) Config successfully loaded.
[2020-04-27 08:45:48,071] fb2cal INFO (main) Logging level set to: INFO
[2020-04-27 08:45:48,072] fb2cal INFO (main) Attemping to authenticate with Facebook...
[2020-04-27 08:45:51,338] fb2cal ERROR (facebook_authenticate) Hit Facebook security checkpoint. Please login to Facebook manually and follow prompts to authorize this device.
Traceback (most recent call last):
  File "src/fb2cal.py", line 815, in <module>
    main()
  File "src/fb2cal.py", line 112, in main
    facebook_authenticate(browser, config['AUTH']['FB_EMAIL'], config['AUTH']['FB_PASS'])
  File "src/fb2cal.py", line 262, in facebook_authenticate
    raise SystemError
SystemError
```

**Comment by albertoZurini** [comment]
Disabling 2SA made this script working
[https://github.com/mobeigi/fb2cal/issues/9](https://github.com/mobeigi/fb2cal/issues/9)
