### ISSUE TITLE
ValueError: day is out of range for month

### ISSUE THREAD

**Issue by davemcwish1** [mobeigi/fb2cal#66]
Hi, I had a few problems with environment conflicts but got the script to run. The console (only) its showing the following at the tail:-

`[2020-05-09 13:02:42,399] fb2cal INFO (main) A total of 99 birthdays were found.
[2020-05-09 13:02:42,399] fb2cal INFO (main) Creating birthday ICS file...
Traceback (most recent call last):
  File "src/fb2cal.py", line 815, in <module>
    main()
  File "src/fb2cal.py", line 127, in main
    c = populate_birthdays_calendar(birthdays)
  File "src/fb2cal.py", line 800, in populate_birthdays_calendar
    e.begin = f'{year}-{month}-{day} 00:00:00'
  File "/Users/davidwishart/.pyenv/versions/3.7.7/lib/python3.7/site-packages/ics/event.py", line 155, in begin
    value = get_arrow(value)
  File "/Users/davidwishart/.pyenv/versions/3.7.7/lib/python3.7/site-packages/ics/utils.py", line 196, in get_arrow
    return arrow.get(value)
  File "/Users/davidwishart/.pyenv/versions/3.7.7/lib/python3.7/site-packages/arrow/api.py", line 21, in get
    return _factory.get(*args, **kwargs)
  File "/Users/davidwishart/.pyenv/versions/3.7.7/lib/python3.7/site-packages/arrow/factory.py", line 207, in get
    dt = parser.DateTimeParser(locale).parse_iso(arg)
  File "/Users/davidwishart/.pyenv/versions/3.7.7/lib/python3.7/site-packages/arrow/parser.py", line 131, in parse_iso
    return self._parse_multiformat(string, formats)
  File "/Users/davidwishart/.pyenv/versions/3.7.7/lib/python3.7/site-packages/arrow/parser.py", line 312, in _parse_multiformat
    _datetime = self.parse(string, fmt)
  File "/Users/davidwishart/.pyenv/versions/3.7.7/lib/python3.7/site-packages/arrow/parser.py", line 205, in parse
    return self._build_datetime(parts)
  File "/Users/davidwishart/.pyenv/versions/3.7.7/lib/python3.7/site-packages/arrow/parser.py", line 301, in _build_datetime
    tzinfo=parts.get("tzinfo"),
ValueError: day is out of range for month`

The Debug logging to logs\fb2cal.log has the last line of

`[2020-05-09 13:02:42,399] fb2cal INFO (main) Creating birthday ICS file...`

My source system is macos Catalina 10.15.4 with Python 3.7.7 configured.

Any idea ?

**Comment by davemcwish1** [comment]
Duplicate of [ValueError: day is out of range for month #57](https://github.com/mobeigi/fb2cal/issues/57).
